git:
  submodules: false
language: scala
sudo: required
cache:
  apt: true
  directories:
    $HOME/.ivy2
    toolchain
    verisim/verilator

# packages needed to build riscv-tools
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - device-tree-compiler
      - libusb-1.0-0-dev
      - python-pexpect

jobs:
  include:
    - stage: prepare cache-riscv-tools
      script:
        - travis_wait 120 make tools -C regression SUITE=none
      before_install:
        - export CXX=g++-4.8 CC=gcc-4.8 RISCV=toolchain
    - stage: prepare cache-verilator
      script:
        - travis_wait 120 make verilator -C verisim SUITE=none
      before_install:
        - export CXX=g++-4.8 CC=gcc-4.8 RISCV=toolchain
    - &test_emulator
      stage: Test
      script:
        - travis_wait 80 make $(TEST_CONFIG) -C verisim
        - travis_wait 80 make run-asm-tests $(TEST_CONFIG) -C verisim
        - travis_wait 80 make run-bmark-tests $(TEST_CONFIG) -C verisim
      before_script:
        - TEST_CONFIG=''
    - <<: *test_emulator
      before_script:
        - TEST_CONFIG='CONFIG=SmallBoomConfig'
    - <<: *test_emulator
      before_script:
        - TEST_CONFIG='CONFIG=MediumBoomConfig'
    - <<: *test_emulator
      before_script:
        - TEST_CONFIG='CONFIG=MegaBoomConfig'
    - &test_vsim
      stage: Test
      script:
        - travis_wait 80 make verilog $(TEST_CONFIG) -C vsim
      before_script:
        - TEST_CONFIG='CONFIG=jtagSmallBoomConfig'
    - <<: *test_vsim
      before_script:
        - TEST_CONFIG='CONFIG=jtagMediumBoomConfig'
    - <<: *test_vsim
      before_script:
        - TEST_CONFIG='CONFIG=jtagMegaBoomConfig'
