git:
  submodules: false
language: scala
sudo: required
cache:
  apt: true
  directories:
    $HOME/.ivy2
    toolchain
    verisim/verilator

# packages needed to build riscv-tools
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - device-tree-compiler
      - libusb-1.0-0-dev
      - python-pexpect

jobs:
  include:
    - stage: prepare cache-riscv-tools
      script:
        - scripts/build-tools.sh
      before_install:
        - export CXX=g++-4.8 CC=gcc-4.8 RISCV=`pwd`/toolchain
    - stage: prepare cache-verilator
      script:
        - scripts/init-submodules-no-riscv-tools.sh
        - make verilator -C verisim
      before_install:
        - export CXX=g++-4.8 CC=gcc-4.8 RISCV=`pwd`/toolchain
    - &test_emulator
      stage: Test
      script:
        - scripts/init-submodules-no-riscv-tools.sh
        - make $(TEST_CONFIG) -C verisim
        - make run-asm-tests $(TEST_CONFIG) -C verisim
        - make run-bmark-tests $(TEST_CONFIG) -C verisim
      before_script:
        - export RISCV=`pwd`/toolchain TEST_CONFIG=''
    - <<: *test_emulator
      before_script:
        - export RISCV=`pwd`/toolchain TEST_CONFIG='CONFIG=SmallBoomConfig'
    - <<: *test_emulator
      before_script:
        - export RISCV=`pwd`/toolchain TEST_CONFIG='CONFIG=MediumBoomConfig'
    - <<: *test_emulator
      before_script:
        - export RISCV=`pwd`/toolchain TEST_CONFIG='CONFIG=MegaBoomConfig'
    - &test_vsim
      stage: Test
      script:
        - scripts/init-submodules-no-riscv-tools.sh
        - make verilog $(TEST_CONFIG) -C vsim
      before_script:
        - export RISCV=`pwd`/toolchain TEST_CONFIG='CONFIG=jtagSmallBoomConfig'
    - <<: *test_vsim
      before_script:
        - export RISCV=`pwd`/toolchain TEST_CONFIG='CONFIG=jtagMediumBoomConfig'
    - <<: *test_vsim
      before_script:
        - export RISCV=`pwd`/toolchain TEST_CONFIG='CONFIG=jtagMegaBoomConfig'
